project:
  type: book
  output-dir: docs

book:
  title: "FEFACCION 2025"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_preparation.qmd
      chapters: 
        - 11_traits.qmd
        - 12_protocols.qmd
        - 13_material.qmd
        - 14_maps.qmd
  appendices:
    - 97_meeting.qmd
    - 99_references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
